# Generated by Django 4.2 on 2023-04-21 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentcontrol', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='assigned_crm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=2)),
                ('zip', models.IntegerField(max_length=5)),
                ('assigned_to', models.CharField(max_length=150)),
                ('notes', models.TextField()),
                ('date_added', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='unassigned_crm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('notes', models.TextField()),
                ('date_added', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='crm_items_model',
        ),
    ]
