# Generated by Django 4.2 on 2023-04-21 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentcontrol', '0003_alter_assigned_crm_zip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assigned_crm',
            name='zip',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
