# Generated by Django 4.2 on 2023-04-25 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contentcontrol', '0005_assigned_record_unassigned_record_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='unassigned_record',
        ),
    ]
